name: vhelp_test
version: 1.0.0+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_calendar: ^19.2.55
  cupertino_icons: ^1.0.2
  splashscreen: any
  form_field_validator: ^1.1.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.0.1
  fluttertoast: ^8.0.8
  # device_calendar: ^3.1.0
  # database storage
  sqflite: ^2.0.0+3
  # format date time
  intl: ^0.17.0
   # display todos in grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_local_notifications: ^8.1.1+1
  flutter_emoji: ^2.2.1+1
  connectivity: ^3.0.6
  provider: ^6.0.0
  url_launcher: ^6.0.20
  cloud_firestore: ^2.5.1
  shared_preferences: ^2.0.7
  logger: ^1.1.0
  path_provider: ^2.0.5
  http: ^0.13.4
  rxdart: ^0.27.1
  flutter_native_timezone: ^2.0.0
  timezone: ^0.8.0
  youtube_player_flutter: ^8.0.0
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4+2
  file_picker: ^4.1.4
  image: ^3.0.8
  firebase_storage: ^10.0.5
  carousel_slider: ^4.0.0
  firebase_database: ^8.0.0
  awesome_notifications: ^0.0.6+11
  font_awesome_flutter: ^9.2.0
  flutter_speed_dial: ^4.6.0
  flutter_secure_storage: ^4.2.1
  flutter_bloc: ^7.3.1
  get_it: ^7.2.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  date_picker_timeline: ^1.2.3
  flutter_svg: ^0.23.0+1
  restart_app: ^1.1.0
  path: ^1.8.0
  flutter_cache_manager: ^3.3.0
  assets_audio_player: ^3.0.3+9
  youtube_player_iframe: ^2.2.2
  audioplayers: ^0.20.1
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
  - assets/sounds/
